
services:
  neo4j:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
      - ./import/:/import/
    environment:
    
      # DB_HOST and DB_PORT values would appear in command-line output as:
      # Remote interface available at http://localhost:7474/
      # - DB_HOST=localhost
      # - DB_PORT=7474

      # Make sure this matches the NEO4J_AUTH environment variable declared in ./neo4j/v4.x.x/Dockerfile
      - NEO4J_AUTH=neo4j/Your-Password

    restart: always



