
services:
  neo4j:
    images: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
    
      # DB_HOST and DB_PORT values would appear in command-line output as:
      # Remote interface available at http://localhost:7474/
      - DB_HOST=localhost
      - DB_PORT=7474

      # Make sure this matches the NEO4J_AUTH environment variable declared in ./neo4j/v4.x.x/Dockerfile
      - DB_USER=neo4j
      - DB_PASSWORD=letmein

    restart: always