
services:
  neo4j:
    image: neo4j:latest
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j_data/logs:/logs
      - ./neo4j_data/config:/config
      - ./neo4j_data/data:/data
      - ./neo4j_data/plugins:/plugins
      - ./neo4j_data/import:/import
    # env_file:
    #   - .env
    environment:
      # Make sure this matches the NEO4J_AUTH environment variable declared in ./neo4j/v4.x.x/Dockerfile
<<<<<<< HEAD
      - NEO4J_AUTH=neo4j/NEO4J_PASSWORD
    env_file:
      - ./.env 
=======
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
>>>>>>> 94f7373 (Fixing uses environments variable)
    restart: always

    secrets:
      - neo4j_auth_file

secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt
